In [9]:
import numpy as np

# 4.1 Exercise on Functions

## Task 1: Unit Converter
Create a Python program that converts between different units of measurement (Length, Weight, Volume). The program prompts the user to choose a conversion type, input a value, performs the conversion, handles errors, and displays the result.

In [2]:
def convert_length(value, direction):
    """
    Converts length between meters and feet.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'm_to_ft' or 'ft_to_m'
    Returns:
        float: The converted value.
    """
    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction. Use 'm_to_ft' or 'ft_to_m'.")

def convert_weight(value, direction):
    """
    Converts weight between kilograms and pounds.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'kg_to_lbs' or 'lbs_to_kg'
    Returns:
        float: The converted value.
    """
    if direction == 'kg_to_lbs':
        return value * 2.20462
    elif direction == 'lbs_to_kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction. Use 'kg_to_lbs' or 'lbs_to_kg'.")

def convert_volume(value, direction):
    """
    Converts volume between liters and gallons.
    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'l_to_gal' or 'gal_to_l'
    Returns:
        float: The converted value.
    """
    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction. Use 'l_to_gal' or 'gal_to_l'.")

def unit_converter():
    """
    Main function that prompts user to choose conversion type and value.
    Returns:
        float: The converted result.
    """
    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = input("Enter 1, 2, or 3: ")

        if choice == "1":
            print("a. Meters to Feet  b. Feet to Meters")
            sub = input("Enter a or b: ")
            value = float(input("Enter value: "))
            direction = 'm_to_ft' if sub == 'a' else 'ft_to_m'
            result = convert_length(value, direction)
            print(f"Result: {result:.4f}")

        elif choice == "2":
            print("a. Kg to Lbs  b. Lbs to Kg")
            sub = input("Enter a or b: ")
            value = float(input("Enter value: "))
            direction = 'kg_to_lbs' if sub == 'a' else 'lbs_to_kg'
            result = convert_weight(value, direction)
            print(f"Result: {result:.4f}")

        elif choice == "3":
            print("a. Liters to Gallons  b. Gallons to Liters")
            sub = input("Enter a or b: ")
            value = float(input("Enter value: "))
            direction = 'l_to_gal' if sub == 'a' else 'gal_to_l'
            result = convert_volume(value, direction)
            print(f"Result: {result:.4f}")

        else:
            print("Invalid choice. Please enter 1, 2, or 3.")
            return None

        return result

    except ValueError as e:
        print(f"Error: Invalid input! Please enter a numeric value. Details: {e}")
        return None

# Run the converter
unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter 1, 2, or 3: 1
a. Meters to Feet  b. Feet to Meters
Enter a or b: a
Enter value: 160
Result: 524.9344


524.9344

## Task 2: Mathematical Operations on a List
Create a Python program that performs various mathematical operations (sum, average, maximum, minimum) on a user-inputted list of numbers, with error handling for invalid inputs and empty lists.

In [3]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The sum of all numbers in the list.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The average of all numbers in the list.
    """
    return sum(numbers) / len(numbers)

def calculate_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The maximum value in the list.
    """
    return max(numbers)

def calculate_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.
    Parameters:
        numbers (list): A list of numeric values.
    Returns:
        float: The minimum value in the list.
    """
    return min(numbers)

def math_operations():
    """
    Main function that prompts user to choose an operation
    and input a list of numbers, then performs the operation.
    Returns:
        float: The result of the selected operation.
    """
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = input("Enter 1, 2, 3, or 4: ")
        numbers = input("Enter numbers separated by spaces: ")

        # Convert input string to list of floats
        numbers = [float(x) for x in numbers.split()]

        if len(numbers) == 0:
            raise ValueError("List is empty!")

        if choice == "1":
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == "2":
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == "3":
            result = calculate_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == "4":
            result = calculate_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid choice!")
            return None

        return result

    except ValueError as e:
        print(f"Error: Invalid input! {e}")
        return None

# Run the function
math_operations()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 3
Enter numbers separated by spaces: 5 6
Maximum: 6.0


6.0

# 4.2 Exercise on List Manipulation

## 1. Extract Every Other Element:


In [14]:
def extract_every_other(lst):
    """
    Extracts every other element starting from the first.
    Parameters:
        lst (list): Input list.
    Returns:
        list: Every other element starting from index 0.
    """
    return lst[::2]

## 2. Slice a Sublist:


In [15]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from start to end index (inclusive).
    Parameters:
        lst (list): Input list.
        start (int): Starting index.
        end (int): Ending index (inclusive).
    Returns:
        list: Sublist from start to end.
    """
    return lst[start:end+1]


## 3. Reverse a List Using Slicing:

In [16]:
def reverse_list(lst):
    """
    Reverses a list using slicing.
    Parameters:
        lst (list): Input list.
    Returns:
        list: Reversed list.
    """
    return lst[::-1]

## 4. Remove the First and Last Elements:

In [17]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.
    Parameters:
        lst (list): Input list.
    Returns:
        list: List without first and last elements.
    """
    return lst[1:-1]

## 5. Get the First n Elements:

In [18]:
def get_first_n(lst, n):
    """
    Returns the first n elements of a list.
    Parameters:
        lst (list): Input list.
        n (int): Number of elements to return.
    Returns:
        list: First n elements.
    """
    return lst[:n]

## 6. Extract Elements from the End:

In [19]:
def get_last_n(lst, n):
    """
    Returns the last n elements of a list.
    Parameters:
        lst (list): Input list.
        n (int): Number of elements to return.
    Returns:
        list: Last n elements.
    """
    return lst[-n:]

## 7. Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
    """
    Returns every second element starting from second-to-last, moving backward.
    Parameters:
        lst (list): Input list.
    Returns:
        list: Every second element in reverse order.
    """
    return lst[-2::-2]

## Testing All Functions:

In [21]:
# Testing all functions
lst1 = [1, 2, 3, 4, 5, 6]
lst2 = [1, 2, 3, 4, 5]

print("Original list:", lst1)
print("1. Extract every other:", extract_every_other(lst1))
print("2. Sublist (index 2 to 4):", get_sublist(lst1, 2, 4))
print("3. Reversed:", reverse_list(lst2))
print("4. Remove first and last:", remove_first_last(lst2))
print("5. First 3 elements:", get_first_n(lst2, 3))
print("6. Last 2 elements:", get_last_n(lst2, 2))
print("7. Reverse skip:", reverse_skip(lst1))

Original list: [1, 2, 3, 4, 5, 6]
1. Extract every other: [1, 3, 5]
2. Sublist (index 2 to 4): [3, 4, 5]
3. Reversed: [5, 4, 3, 2, 1]
4. Remove first and last: [2, 3, 4]
5. First 3 elements: [1, 2, 3]
6. Last 2 elements: [4, 5]
7. Reverse skip: [5, 3, 1]


# 4.3 Exercise on Nested List


## 1. Flatten a Nested List:

In [30]:
def flatten(lst):
    """
    Flattens a nested list into a single list.
    Parameters:
        lst (list): A nested list.
    Returns:
        list: A flattened single-dimension list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

## 2. Accessing Nested List Elements:


In [31]:
def access_nested_element(lst, indices):
    """
    Accesses a specific element in a nested list using indices.
    Parameters:
        lst (list): A nested list.
        indices (list): List of indices to navigate to the element.
    Returns:
        The element at the specified position.
    """
    for index in indices:
        lst = lst[index]
    return lst

## 3. Sum of All Elements in a Nested List:


In [32]:
def sum_nested(lst):
    """
    Calculates the sum of all elements in a nested list.
    Parameters:
        lst (list): A nested list.
    Returns:
        float: Sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

## 4. Remove Specific Element from a Nested List:

In [33]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.
    Parameters:
        lst (list): A nested list.
        elem: The element to remove.
    Returns:
        list: Modified nested list with element removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

## 5. Find the Maximum Element in a Nested List:

In [34]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.
    Parameters:
        lst (list): A nested list.
    Returns:
        The maximum element.
    """
    flat = flatten(lst)
    return max(flat)

## 6. Count Occurrences of an Element in a Nested List:


In [35]:
def count_occurrences(lst, elem):
    """
    Counts occurrences of a specific element in a nested list.
    Parameters:
        lst (list): A nested list.
        elem: The element to count.
    Returns:
        int: Number of occurrences.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

## 7. Flatten a List of Lists of Lists:


In [36]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list regardless of depth.
    Parameters:
        lst (list): A deeply nested list.
    Returns:
        list: A fully flattened single-dimension list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

## 8. Nested List Average:


In [37]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.
    Parameters:
        lst (list): A nested list.
    Returns:
        float: Average of all elements.
    """
    flat = flatten(lst)
    return sum(flat) / len(flat)

## Testing all functions


In [38]:
print("1. Flatten:", flatten([[1, 2], [3, 4], [5]]))
print("2. Access nested element:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))
print("3. Sum nested:", sum_nested([[1, 2], [3, [4, 5]], 6]))
print("4. Remove element:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("5. Find max:", find_max([[1, 2], [3, [4, 5]], 6]))
print("6. Count occurrences:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("7. Deep flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("8. Average nested:", average_nested([[1, 2], [3, 4], [5, 6]]))

1. Flatten: [1, 2, 3, 4, 5]
2. Access nested element: 6
3. Sum nested: 21
4. Remove element: [[1], [3], [4, 5]]
5. Find max: 6
6. Count occurrences: 3
7. Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average nested: 3.5


# 10.1 Basic Vector and Matrix Operation with Numpy.


## Problem - 1: Array Creation:



### 1. Initialize an empty array with size 2X2.

In [56]:
empty_arr = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_arr)

1. Empty 2x2 array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


### 2. Initialize an all one array with size 4X2.

In [46]:
ones_arr = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_arr)


2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### 3. Return a new array of given shape and type, filled with fill value.

In [51]:
filled_arr = np.full((3, 3), 7)
print("\n3. Array filled with 7:\n", filled_arr)


3. Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


### 4. Return a new array of zeros with same shape and type as a given array.

In [52]:
existing = np.array([[1, 2], [3, 4]])
zeros_like_arr = np.zeros_like(existing)
print("\n4. Zeros like existing array:\n", zeros_like_arr)


4. Zeros like existing array:
 [[0 0]
 [0 0]]


### 5. Return a new array of ones with same shape and type as a given array.

In [53]:
ones_like_arr = np.ones_like(existing)
print("\n5. Ones like existing array:\n", ones_like_arr)


5. Ones like existing array:
 [[1 1]
 [1 1]]


### 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.

In [54]:
new_list = [1, 2, 3, 4]
numpy_arr = np.array(new_list)
print("\n6. List converted to numpy array:", numpy_arr)



6. List converted to numpy array: [1 2 3 4]


## Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

### 1. Create an array with values ranging from 10 to 49.

In [55]:
arr_range = np.arange(10, 50)
print("1. Array from 10 to 49:\n", arr_range)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 2. Create a 3X3 matrix with values ranging from 0 to 8.

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0 to 8):\n", matrix_3x3)

### 3. Create a 3X3 identity matrix.

In [ ]:
identity = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity)

### 4. Create a random array of size 30 and find the mean of the array.

In [ ]:
random_arr = np.random.random(30)
print("\n4. Random array mean:", random_arr.mean())

### 5. Create a 10X10 array with random values and find the minimum and maximum values.


In [ ]:
random_10x10 = np.random.random((10, 10))
print("\n5. 10x10 array - Min:", random_10x10.min(), "Max:", random_10x10.max())

### 6. Create a zero array of size 10 and replace 5th element with 1.

In [48]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element as 1:\n", zero_arr)


6. Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Reverse an array arr = [1,2,0,0,4,0].

In [49]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:", reversed_arr)


7. Reversed array: [0 4 0 0 2 1]


### 8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border array:\n", border_arr)

### 9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [50]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", checkerboard)


9. Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem - 3: Array Operations:


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

### 1. Add the two array.


In [57]:
print("1. x + y:\n", x + y)

1. x + y:
 [[ 6  8]
 [10 13]]


### 2. Subtract the two array.


In [58]:
print("\n2. x - y:\n", x - y)


2. x - y:
 [[-4 -4]
 [-4 -3]]


### 3. Multiply the array with any integers of your choice.


In [59]:
print("\n3. x * 3:\n", x * 3)


3. x * 3:
 [[ 3  6]
 [ 9 15]]


### 4. Find the square of each element of the array.


In [60]:
print("\n4. x squared:\n", np.square(x))


4. x squared:
 [[ 1  4]
 [ 9 25]]


### 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [61]:
print("\n5. Dot product v.w:", np.dot(v, w))
print("   Dot product x.v:\n", np.dot(x, v))
print("   Dot product x.y:\n", np.dot(x, y))


5. Dot product v.w: 219
   Dot product x.v:
 [29 77]
   Dot product x.y:
 [[19 22]
 [50 58]]


### 6. Concatenate x(and)y along row and Concatenate v(and)w along column.


In [62]:
concat_rows = np.vstack((x, y))
print("\n6. Concatenate x and y along rows:\n", concat_rows)
concat_cols = np.concatenate((v, w))
print("   Concatenate v and w:", concat_cols)


6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
   Concatenate v and w: [ 9 10 11 12]


### 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [63]:
print("\n7. Trying to concatenate x and v:")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"   Error: {e}")
    print("   Explanation: x has shape", x.shape, "and v has shape", v.shape)
    print("   They have different dimensions (2D vs 1D) so they cannot be concatenated directly.")


7. Trying to concatenate x and v:
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Explanation: x has shape (2, 2) and v has shape (2,)
   They have different dimensions (2D vs 1D) so they cannot be concatenated directly.


## Problem - 4: Matrix Operations:


### 1. For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);     
Prove following with Numpy:

#### i. Prove A.A_inverse = I.



In [64]:
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A . A_inverse (should be Identity):\n", np.round(identity))

1. A . A_inverse (should be Identity):
 [[1. 0.]
 [0. 1.]]


#### ii. Prove AB != BA.

In [65]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.array_equal(AB, BA))


2. AB:
 [[23 13]
 [51 29]]
   BA:
 [[36 44]
 [13 16]]
   AB == BA? False


#### iii. Prove (AB)^T = B^T . A^T

In [66]:
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", AB_T)
print("   B^T . A^T:\n", BT_AT)
print("   Are they equal?", np.array_equal(AB_T, BT_AT))


3. (AB)^T:
 [[23 51]
 [13 29]]
   B^T . A^T:
 [[23 51]
 [13 29]]
   Are they equal? True


### 2. Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1     
x − y + 2z = −3     
3x + y − z = 9

In [68]:
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3,  1, -1]])
B_eq = np.array([-1, -3, 9])

# Using inverse method
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("Solution using Inverse Method:")
print(f"x = {X[0]:.2f}, y = {X[1]:.2f}, z = {X[2]:.2f}")

# Using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)
print("\nSolution using np.linalg.solve:")
print(f"x = {X_solve[0]:.2f}, y = {X_solve[1]:.2f}, z = {X_solve[2]:.2f}")

Solution using Inverse Method:
x = 2.00, y = 1.00, z = -2.00

Solution using np.linalg.solve:
x = 2.00, y = 1.00, z = -2.00


# 10.2 Experiment: How Fast is Numpy?

In [69]:
import numpy as np
import time

size = 1_000_000

# Setup data
list_a = list(range(size))
list_b = list(range(size))
np_a = np.arange(size, dtype=float)
np_b = np.arange(size, dtype=float)

## 1. Element-wise Addition:

In [70]:
start = time.time()
result = [list_a[i] + list_b[i] for i in range(size)]
end = time.time()
print(f"   Python List time: {end - start:.5f} seconds")

start = time.time()
result = np_a + np_b
end = time.time()
print(f"   NumPy Array time: {end - start:.5f} seconds")

   Python List time: 0.20932 seconds
   NumPy Array time: 0.02695 seconds


## 2. Element-wise Multiplication


In [71]:
start = time.time()
result = [list_a[i] * list_b[i] for i in range(size)]
end = time.time()
print(f"   Python List time: {end - start:.5f} seconds")

start = time.time()
result = np_a * np_b
end = time.time()
print(f"   NumPy Array time: {end - start:.5f} seconds")

   Python List time: 0.10796 seconds
   NumPy Array time: 0.01510 seconds


## 3. Dot Product


In [72]:
start = time.time()
result = sum(list_a[i] * list_b[i] for i in range(size))
end = time.time()
print(f"   Python List time: {end - start:.5f} seconds")

start = time.time()
result = np.dot(np_a, np_b)
end = time.time()
print(f"   NumPy Array time: {end - start:.5f} seconds")

   Python List time: 0.11020 seconds
   NumPy Array time: 0.00153 seconds


## 4. Matrix Multiplication


In [73]:
mat_size = 1000
list_m1 = [[1.0] * mat_size for _ in range(mat_size)]
list_m2 = [[1.0] * mat_size for _ in range(mat_size)]
np_m1 = np.ones((mat_size, mat_size))
np_m2 = np.ones((mat_size, mat_size))

start = time.time()
result = [[sum(list_m1[i][k] * list_m2[k][j]
           for k in range(mat_size))
           for j in range(mat_size)]
           for i in range(mat_size)]
end = time.time()
print(f"   Python List time: {end - start:.5f} seconds")

start = time.time()
result = np.dot(np_m1, np_m2)
end = time.time()
print(f"   NumPy Array time: {end - start:.5f} seconds")

print("\n✓ Experiment complete! NumPy is significantly faster!")

   Python List time: 127.56853 seconds
   NumPy Array time: 0.08454 seconds

✓ Experiment complete! NumPy is significantly faster!
